instagram_block.settings:
  type: config_object
  label: 'Instagram Block Settings'
  mapping:
    user_id:
      type: label
      label: 'User ID'
    access_token:
      type: label
      label: 'Access Token'
